spring:
  application:
    name: demoEmployees

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/employees_management}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:12345}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none # Para evitar conflictos con liquibase
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yaml

  app:
    jwt-secret: dd1c0c25edf2320965c59832612f58a9ab84f99ce66f8c3ae559fef5bc85fb58
    jwt-expiration-time: 86400000 # 100 days
