spring:
  application:
    name: demoEmployees

  datasource:
    url: ${DATABASE_URL} # Example: jdbc:postgresql://db:5432/employees_management
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yaml

app:
  #Important note: the JWT secret must be a valid Base64 string and sufficiently long (minimum 32 bytes for HS256). For example
  jwt-secret: ${JWT_SECRET} # Example Base64 encoded secret
  jwt-expiration-time: ${JWT_EXPIRATION_TIME} # 1 hour in milliseconds